# Site settings
title: "Adaptive Web Design"
subtitle: "Crafting Rich Experiences with Progressive Enhancement"
email: aaron+awd@aaron-gustafson.com
description: >
  Forthcoming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adaptivewebdesign.info" # the base hostname & protocol for your site
twitter_username: AdaptiveWebNews
book_photo: http://adaptivewebdesign.info/2nd-edition/cover-320.png

# Build settings
markdown: kramdown

# Navigation
navigation:
  - url: /1st-edition/
    title: First Edition
    subnav:
      - url: /1st-edition/read/
        title: Read it Free
      - url: /1st-edition/reviews/
        title: Reviews
      - url: /1st-edition/errata/
        title: Errata
  - url: /2nd-edition/
    title: Second Edition
    subnav:
      - url: "http://www.amazon.com/gp/product/0134216148/ref=as_li_tl?ie=UTF8&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0134216148&amp;linkCode=as2&amp;tag=easydesign-20&amp;linkId=7EDENIS3P4XL7LIT"
        title: Buy from Amazon
      - url: "http://click.linksynergy.com/link?id=ksYXFf8a/VY&amp;offerid=145244.2319719&amp;type=2&amp;murl=http%3A%2F%2Fwww.peachpit.com%2Ftitle%2F9780134216140"
        title: Buy from New Riders
      - url: /2nd-edition/read/forward.html
        title: Foreword
      - url: /2nd-edition/reviews/
        title: Reviews
      - url: /2nd-edition/videos/
        title: Videos
      - url: /2nd-edition/errata/
        title: Errata